# Generated by Django 5.1 on 2024-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/NoImg.jpg', upload_to='images/'),
        ),
    ]
