# Generated by Django 5.1 on 2024-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_price',
            new_name='item_price',
        ),
    ]
