# Generated by Django 5.1 on 2024-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_item_price_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='static/food/images/placeholder_food.png', max_length=500),
        ),
    ]
