# Generated by Django 5.1 on 2024-08-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/003/170/825/non_2x/isolated-food-plate-fork-and-spoon-design-free-vector.jpg', max_length=500),
        ),
    ]
